<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-1819MVE" name="testscript.Auro_Stage_Home_PAge_New" tests="1" failures="1" timestamp="2020-12-10T16:01:32 IST" time="46.406" errors="0">
  <testcase name="select_LoseWeight_Beginner_Spin_Availoffer_Dothe_Payment_Entering_Credentials_Incorrect_Security_Code" time="46.406" classname="testscript.Auro_Stage_Home_PAge_New">
    <failure type="java.lang.AssertionError" message="expected [Your card&#039;s security code is incorrect.] but found [Credit card number
Your card&#039;s security code is incorrect.]">
      <![CDATA[java.lang.AssertionError: expected [Your card's security code is incorrect.] but found [Credit card number
Your card's security code is incorrect.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at generic.Base_Page.getText(Base_Page.java:59)
at pom.Auro_Checkout_Page.verifyIncorrectSecurityCodeMessage(Auro_Checkout_Page.java:187)
at testscript.Auro_Stage_Home_PAge_New.select_LoseWeight_Beginner_Spin_Availoffer_Dothe_Payment_Entering_Credentials_Incorrect_Security_Code(Auro_Stage_Home_PAge_New.java:489)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner$$Lambda$51/423583818.accept(Unknown Source)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- select_LoseWeight_Beginner_Spin_Availoffer_Dothe_Payment_Entering_Credentials_Incorrect_Security_Code -->
  <system-out/>
</testsuite> <!-- testscript.Auro_Stage_Home_PAge_New -->
